# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
xcode_workspace: Example/JWInfiniteCollectionView.xcworkspace
cache: cocoapods
podfile: Example/Podfile
# xcode_sdk:  
xcode_scheme: JWInfiniteCycleView_Example
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- xcodebuild build -workspace Example/JWInfiniteCycleView.xcworkspace -scheme JWInfiniteCycleView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/JWInfiniteCycleView.xcworkspace -scheme JWInfiniteCycleView-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty

- pod lib lint

